### ISSUE TITLE
Incompatible with Event Espresso 4.6.0

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-event-espresso#2]
The Event Espresso extension causes a `Fatal error: Class 'EE_Offsite_Gateway' not found in /wp-content/plugins/pronamic-ideal/vendor/wp-pay-extensions/event-espresso/src/IDealGateway.php on line 11`.

There's no file `/wp-content/plugins/event-espresso/core/db_classes/EE_Offsite_Gateway.class.php` in EE 4.6.4.p anymore.

**Comment by rvdsteege** [comment]
See also "For Developers" at http://eventespresso.com/2015/02/major-release-update-4-6-now-available/

**Comment by remcotolsma** [comment]
Just fixed the fatal error: https://github.com/wp-pay-extensions/event-espresso/commit/48c55f4031db4566f3299e79d32e758171d6f2b2. Unfortunately it's not easy to make the library compatible with Event Espresso 4.6. We have to rewrite the code completely and have to think about backward compatibility  for version > 4.0 < 4.6.

**Comment by rvdsteege** [comment]
Issue solved in https://github.com/wp-pay-extensions/event-espresso/commit/10c1112abb9825ad66b6280c6abead81c9111e63
