### ISSUE TITLE
Set payment status not working for Event Espresso

### ISSUE THREAD

**Issue by edwinsiebel** [pronamic/wp-pronamic-pay-event-espresso#3]
Have all day been debugging where, when and how the payment status is determined and set, or in my case even, not correctly set.

Eventually, I think I have figured it out. In file `Extension.php` for the Event Espresso extension, on line 169-170, states the following:

``` php
$ee_payment = $ee_transaction->last_payment();
$ee_payment->set_status( $status );
```

The status is correctly set, when var_dumping $ee_payment.

Then on line 172-173:

``` php
$payment_processor = EE_Registry::instance()->load_core( 'Payment_Processor' );
$payment_processor->finalize_payment_for( $ee_transaction, true );
```

Thus, the $payment_processor->finalize_payment_for( ) is been fed the $ee_transaction, with the **incorrect** status, instead of the $ee_payment, with the **correct** status.
Of course, $ee_payment will not be able to be passed to $payment_processor->finalize_payment_for( ).

So, either I'm completely on the wrong track, or there is something very wrong. Can you help me out?

**Comment by rvdsteege** [comment]
The payment status is set and saved to the transaction in https://github.com/wp-pay-extensions/event-espresso/blob/develop/src/IDealGateway.php#L199-L203

Which WordPress and Event Espresso versions and which payment provider are you using?

**Comment by edwinsiebel** [comment]
Thx for the quick reply.

I've seen that, however, the function update_status_unknown_to_success() is never called, as if the action **pronamic_payment_status_update_eventespresso_unknown_to_success** is never executed.

The action **pronamic_payment_status_update_eventespresso** is executed, however the function status_update() does not have the save function, as described in update_status_unknown_to_success.

I'm using WP 4.2.2, and EE 4.7.6.p.

**Comment by edwinsiebel** [comment]
Hi rvdsteege,

By any chance, did you have time to look at this? Is it a bug, or am I doing something wrong/stupid?

Thanks

Edwin
